// AUTO-GENERATED by scripts/generate-registry.ts — do not edit by hand.
// Run `npm run generate-registry` after adding or removing components.

export { default as Accordion } from "./accordion/Accordion.astro";
export { default as AccordionContent } from "./accordion/AccordionContent.astro";
export { default as AccordionItem } from "./accordion/AccordionItem.astro";
export { default as AccordionTrigger } from "./accordion/AccordionTrigger.astro";

export { default as Alert } from "./alert/Alert.astro";
export { default as AlertDescription } from "./alert/AlertDescription.astro";
export { default as AlertTitle } from "./alert/AlertTitle.astro";

export { default as AlertDialog } from "./alert-dialog/AlertDialog.astro";
export { default as AlertDialogAction } from "./alert-dialog/AlertDialogAction.astro";
export { default as AlertDialogCancel } from "./alert-dialog/AlertDialogCancel.astro";
export { default as AlertDialogContent } from "./alert-dialog/AlertDialogContent.astro";
export { default as AlertDialogDescription } from "./alert-dialog/AlertDialogDescription.astro";
export { default as AlertDialogFooter } from "./alert-dialog/AlertDialogFooter.astro";
export { default as AlertDialogHeader } from "./alert-dialog/AlertDialogHeader.astro";
export { default as AlertDialogOverlay } from "./alert-dialog/AlertDialogOverlay.astro";
export { default as AlertDialogTitle } from "./alert-dialog/AlertDialogTitle.astro";
export { default as AlertDialogTrigger } from "./alert-dialog/AlertDialogTrigger.astro";

export { default as AspectRatio } from "./aspect-ratio/AspectRatio.astro";

export { default as Avatar } from "./avatar/Avatar.astro";
export { default as AvatarFallback } from "./avatar/AvatarFallback.astro";
export { default as AvatarGroup } from "./avatar/AvatarGroup.astro";
export { default as AvatarImage } from "./avatar/AvatarImage.astro";

export { default as Badge } from "./badge/Badge.astro";

export { default as Breadcrumb } from "./breadcrumb/Breadcrumb.astro";
export { default as BreadcrumbEllipsis } from "./breadcrumb/BreadcrumbEllipsis.astro";
export { default as BreadcrumbItem } from "./breadcrumb/BreadcrumbItem.astro";
export { default as BreadcrumbLink } from "./breadcrumb/BreadcrumbLink.astro";
export { default as BreadcrumbList } from "./breadcrumb/BreadcrumbList.astro";
export { default as BreadcrumbPage } from "./breadcrumb/BreadcrumbPage.astro";
export { default as BreadcrumbSeparator } from "./breadcrumb/BreadcrumbSeparator.astro";

export { default as Button } from "./button/Button.astro";

export { default as ButtonGroup } from "./button-group/ButtonGroup.astro";
export { default as ButtonGroupSeparator } from "./button-group/ButtonGroupSeparator.astro";
export { default as ButtonGroupText } from "./button-group/ButtonGroupText.astro";

export { default as Card } from "./card/Card.astro";
export { default as CardAction } from "./card/CardAction.astro";
export { default as CardContent } from "./card/CardContent.astro";
export { default as CardDescription } from "./card/CardDescription.astro";
export { default as CardFooter } from "./card/CardFooter.astro";
export { default as CardHeader } from "./card/CardHeader.astro";
export { default as CardTitle } from "./card/CardTitle.astro";

export { default as Carousel } from "./carousel/Carousel.astro";
export { default as CarouselContent } from "./carousel/CarouselContent.astro";
export { default as CarouselDots } from "./carousel/CarouselDots.astro";
export { default as CarouselItem } from "./carousel/CarouselItem.astro";
export { default as CarouselNext } from "./carousel/CarouselNext.astro";
export { default as CarouselPrevious } from "./carousel/CarouselPrevious.astro";
export { default as CarouselThumbnail } from "./carousel/CarouselThumbnail.astro";
export { default as CarouselThumbnails } from "./carousel/CarouselThumbnails.astro";

export { default as Checkbox } from "./checkbox/Checkbox.astro";

export { default as Collapsible } from "./collapsible/Collapsible.astro";
export { default as CollapsibleContent } from "./collapsible/CollapsibleContent.astro";
export { default as CollapsibleTrigger } from "./collapsible/CollapsibleTrigger.astro";

export { default as Combobox } from "./combobox/Combobox.astro";
export { default as ComboboxContent } from "./combobox/ComboboxContent.astro";
export { default as ComboboxItem } from "./combobox/ComboboxItem.astro";
export { default as ComboboxTrigger } from "./combobox/ComboboxTrigger.astro";

export { default as Command } from "./command/Command.astro";
export { default as CommandDialog } from "./command/CommandDialog.astro";
export { default as CommandDialogContent } from "./command/CommandDialogContent.astro";
export { default as CommandDialogOverlay } from "./command/CommandDialogOverlay.astro";
export { default as CommandDialogTrigger } from "./command/CommandDialogTrigger.astro";
export { default as CommandEmpty } from "./command/CommandEmpty.astro";
export { default as CommandGroup } from "./command/CommandGroup.astro";
export { default as CommandInput } from "./command/CommandInput.astro";
export { default as CommandItem } from "./command/CommandItem.astro";
export { default as CommandList } from "./command/CommandList.astro";
export { default as CommandSeparator } from "./command/CommandSeparator.astro";
export { default as CommandShortcut } from "./command/CommandShortcut.astro";

export { default as ContextMenu } from "./context-menu/ContextMenu.astro";
export { default as ContextMenuContent } from "./context-menu/ContextMenuContent.astro";
export { default as ContextMenuItem } from "./context-menu/ContextMenuItem.astro";
export { default as ContextMenuLabel } from "./context-menu/ContextMenuLabel.astro";
export { default as ContextMenuSeparator } from "./context-menu/ContextMenuSeparator.astro";
export { default as ContextMenuShortcut } from "./context-menu/ContextMenuShortcut.astro";
export { default as ContextMenuTrigger } from "./context-menu/ContextMenuTrigger.astro";

export { default as Dialog } from "./dialog/Dialog.astro";
export { default as DialogClose } from "./dialog/DialogClose.astro";
export { default as DialogContent } from "./dialog/DialogContent.astro";
export { default as DialogDescription } from "./dialog/DialogDescription.astro";
export { default as DialogFooter } from "./dialog/DialogFooter.astro";
export { default as DialogHeader } from "./dialog/DialogHeader.astro";
export { default as DialogOverlay } from "./dialog/DialogOverlay.astro";
export { default as DialogTitle } from "./dialog/DialogTitle.astro";
export { default as DialogTrigger } from "./dialog/DialogTrigger.astro";

export { default as DropdownMenu } from "./dropdown-menu/DropdownMenu.astro";
export { default as DropdownMenuContent } from "./dropdown-menu/DropdownMenuContent.astro";
export { default as DropdownMenuItem } from "./dropdown-menu/DropdownMenuItem.astro";
export { default as DropdownMenuLabel } from "./dropdown-menu/DropdownMenuLabel.astro";
export { default as DropdownMenuSeparator } from "./dropdown-menu/DropdownMenuSeparator.astro";
export { default as DropdownMenuTrigger } from "./dropdown-menu/DropdownMenuTrigger.astro";

export { default as Empty } from "./empty/Empty.astro";
export { default as EmptyContent } from "./empty/EmptyContent.astro";
export { default as EmptyDescription } from "./empty/EmptyDescription.astro";
export { default as EmptyHeader } from "./empty/EmptyHeader.astro";
export { default as EmptyMedia } from "./empty/EmptyMedia.astro";
export { default as EmptyTitle } from "./empty/EmptyTitle.astro";

export { default as Field } from "./field/Field.astro";
export { default as FieldDescription } from "./field/FieldDescription.astro";
export { default as FieldError } from "./field/FieldError.astro";
export { default as FieldGroup } from "./field/FieldGroup.astro";
export { default as FieldLabel } from "./field/FieldLabel.astro";

export { default as FileUpload } from "./file-upload/FileUpload.astro";
export { default as FileUploadDropzone } from "./file-upload/FileUploadDropzone.astro";
export { default as FileUploadInput } from "./file-upload/FileUploadInput.astro";
export { default as FileUploadPreview } from "./file-upload/FileUploadPreview.astro";
export { default as FileUploadTrigger } from "./file-upload/FileUploadTrigger.astro";

export { default as HoverCard } from "./hover-card/HoverCard.astro";
export { default as HoverCardContent } from "./hover-card/HoverCardContent.astro";
export { default as HoverCardTrigger } from "./hover-card/HoverCardTrigger.astro";

export { default as HugeIcon } from "./icon/HugeIcon.astro";

export { default as Input } from "./input/Input.astro";

export { default as InputGroup } from "./input-group/InputGroup.astro";
export { default as InputGroupAddon } from "./input-group/InputGroupAddon.astro";
export { default as InputGroupButton } from "./input-group/InputGroupButton.astro";
export { default as InputGroupInput } from "./input-group/InputGroupInput.astro";
export { default as InputGroupText } from "./input-group/InputGroupText.astro";
export { default as InputGroupTextarea } from "./input-group/InputGroupTextarea.astro";

export { default as InputOTP } from "./input-otp/InputOTP.astro";
export { default as InputOTPGroup } from "./input-otp/InputOTPGroup.astro";
export { default as InputOTPSeparator } from "./input-otp/InputOTPSeparator.astro";
export { default as InputOTPSlot } from "./input-otp/InputOTPSlot.astro";

export { default as Kbd } from "./kbd/Kbd.astro";
export { default as KbdGroup } from "./kbd/KbdGroup.astro";

export { default as Label } from "./label/Label.astro";

export { default as Menubar } from "./menubar/Menubar.astro";
export { default as MenubarCheckboxItem } from "./menubar/MenubarCheckboxItem.astro";
export { default as MenubarContent } from "./menubar/MenubarContent.astro";
export { default as MenubarGroup } from "./menubar/MenubarGroup.astro";
export { default as MenubarItem } from "./menubar/MenubarItem.astro";
export { default as MenubarLabel } from "./menubar/MenubarLabel.astro";
export { default as MenubarMegaItem } from "./menubar/MenubarMegaItem.astro";
export { default as MenubarMenu } from "./menubar/MenubarMenu.astro";
export { default as MenubarRadioGroup } from "./menubar/MenubarRadioGroup.astro";
export { default as MenubarRadioItem } from "./menubar/MenubarRadioItem.astro";
export { default as MenubarSeparator } from "./menubar/MenubarSeparator.astro";
export { default as MenubarShortcut } from "./menubar/MenubarShortcut.astro";
export { default as MenubarSub } from "./menubar/MenubarSub.astro";
export { default as MenubarSubContent } from "./menubar/MenubarSubContent.astro";
export { default as MenubarSubTrigger } from "./menubar/MenubarSubTrigger.astro";
export { default as MenubarTrigger } from "./menubar/MenubarTrigger.astro";

export { default as Pagination } from "./pagination/Pagination.astro";
export { default as PaginationContent } from "./pagination/PaginationContent.astro";
export { default as PaginationEllipsis } from "./pagination/PaginationEllipsis.astro";
export { default as PaginationItem } from "./pagination/PaginationItem.astro";
export { default as PaginationLink } from "./pagination/PaginationLink.astro";
export { default as PaginationNext } from "./pagination/PaginationNext.astro";
export { default as PaginationPrevious } from "./pagination/PaginationPrevious.astro";

export { default as Popover } from "./popover/Popover.astro";
export { default as PopoverContent } from "./popover/PopoverContent.astro";
export { default as PopoverTrigger } from "./popover/PopoverTrigger.astro";

export { default as Progress } from "./progress/Progress.astro";

export { default as RadioGroup } from "./radio/RadioGroup.astro";
export { default as RadioGroupItem } from "./radio/RadioGroupItem.astro";

export { default as ScrollArea } from "./scroll-area/ScrollArea.astro";

export { default as Select } from "./select/Select.astro";
export { default as SelectGroup } from "./select/SelectGroup.astro";
export { default as SelectOption } from "./select/SelectOption.astro";

export { default as Separator } from "./separator/Separator.astro";

export { default as Sheet } from "./sheet/Sheet.astro";
export { default as SheetClose } from "./sheet/SheetClose.astro";
export { default as SheetContent } from "./sheet/SheetContent.astro";
export { default as SheetDescription } from "./sheet/SheetDescription.astro";
export { default as SheetFooter } from "./sheet/SheetFooter.astro";
export { default as SheetHeader } from "./sheet/SheetHeader.astro";
export { default as SheetOverlay } from "./sheet/SheetOverlay.astro";
export { default as SheetTitle } from "./sheet/SheetTitle.astro";
export { default as SheetTrigger } from "./sheet/SheetTrigger.astro";

export { default as Sidebar } from "./sidebar/Sidebar.astro";
export { default as SidebarContent } from "./sidebar/SidebarContent.astro";
export { default as SidebarFooter } from "./sidebar/SidebarFooter.astro";
export { default as SidebarGroup } from "./sidebar/SidebarGroup.astro";
export { default as SidebarGroupLabel } from "./sidebar/SidebarGroupLabel.astro";
export { default as SidebarHeader } from "./sidebar/SidebarHeader.astro";
export { default as SidebarMenu } from "./sidebar/SidebarMenu.astro";
export { default as SidebarMenuButton } from "./sidebar/SidebarMenuButton.astro";
export { default as SidebarMenuItem } from "./sidebar/SidebarMenuItem.astro";
export { default as SidebarSeparator } from "./sidebar/SidebarSeparator.astro";
export { default as SidebarTrigger } from "./sidebar/SidebarTrigger.astro";

export { default as Skeleton } from "./skeleton/Skeleton.astro";

export { default as Slider } from "./slider/Slider.astro";

export { default as Spinner } from "./spinner/Spinner.astro";

export { default as Stepper } from "./stepper/Stepper.astro";
export { default as StepperDescription } from "./stepper/StepperDescription.astro";
export { default as StepperItem } from "./stepper/StepperItem.astro";
export { default as StepperSeparator } from "./stepper/StepperSeparator.astro";
export { default as StepperTitle } from "./stepper/StepperTitle.astro";
export { default as StepperTrigger } from "./stepper/StepperTrigger.astro";

export { default as Switch } from "./switch/Switch.astro";

export { default as Table } from "./table/Table.astro";
export { default as TableBody } from "./table/TableBody.astro";
export { default as TableCaption } from "./table/TableCaption.astro";
export { default as TableCell } from "./table/TableCell.astro";
export { default as TableFooter } from "./table/TableFooter.astro";
export { default as TableHead } from "./table/TableHead.astro";
export { default as TableHeader } from "./table/TableHeader.astro";
export { default as TableRow } from "./table/TableRow.astro";

export { default as Tabs } from "./tabs/Tabs.astro";
export { default as TabsContent } from "./tabs/TabsContent.astro";
export { default as TabsList } from "./tabs/TabsList.astro";
export { default as TabsTrigger } from "./tabs/TabsTrigger.astro";

export { default as Textarea } from "./textarea/Textarea.astro";

export { default as ThemeToggle } from "./theme-toggle/ThemeToggle.astro";

export { default as Toaster } from "./toast/Toaster.astro";

export { default as Toggle } from "./toggle/Toggle.astro";
export { default as ToggleGroup } from "./toggle/ToggleGroup.astro";
export { default as ToggleGroupItem } from "./toggle/ToggleGroupItem.astro";

export { default as Tooltip } from "./tooltip/Tooltip.astro";
export { default as TooltipContent } from "./tooltip/TooltipContent.astro";
export { default as TooltipTrigger } from "./tooltip/TooltipTrigger.astro";

export { default as Tree } from "./tree/Tree.astro";
export { default as TreeItem } from "./tree/TreeItem.astro";
export { default as TreeItemChildren } from "./tree/TreeItemChildren.astro";
export { default as TreeItemContent } from "./tree/TreeItemContent.astro";
export { default as TreeItemTrigger } from "./tree/TreeItemTrigger.astro";
